<a href="https://colab.research.google.com/github/saigalsaigal2004-eng/Case_Study_SQL_SAIGAL_S_SUNANDAN./blob/main/Case_Study_SQL_SAIGAL_S_SUNANDAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Case Study on SQL

In [2]:
import sqlite3
import pandas as pd

In [3]:
def load_imdb_database(db_path):
  try:
    conn = sqlite3.connect(db_path)
    print("IMDB database loaded successfully.")
    return conn
  except sqlite3.Error as e:
    print(f"Error loading IMDB database: {e}")
    return None

In [4]:
db_path = "imdb.db"
conn = load_imdb_database(db_path)

if conn:
  print("Connection successful")
  cursor = conn.cursor()

IMDB database loaded successfully.
Connection successful

## Following is the schema of the IMDB database. It lists all tables and their schemas.

In [5]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Database Schema:")
for table in tables:
    table_name = table[0]
    print(f"\nTable: {table_name}")

    cursor.execute(f"PRAGMA table_info({table_name});")
    schema = cursor.fetchall()

    print("Columns:")
    for column in schema:
        cid, name, dtype, notnull, dflt_value, pk = column
        print(f"  - {name} ({dtype}), NOT NULL: {bool(notnull)}, Default: {dflt_value}, Primary Key: {bool(pk)}")

Database Schema:

Table: Movie
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - title (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - year (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - rating (REAL), NOT NULL: False, Default: None, Primary Key: False
  - num_votes (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: Genre
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - GID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: Language
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - LAID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: Country
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - CID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: Location
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - LID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: M_Location
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - LID (REAL), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: M_Country
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - CID (REAL), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: M_Language
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - LAID (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: M_Genre
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - GID (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: Person
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - PID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - Name (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - Gender (TEXT), NOT NULL: False, Default: None, Primary Key: False

Table: M_Producer
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - PID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: M_Director
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - PID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

Table: M_Cast
Columns:
  - index (INTEGER), NOT NULL: False, Default: None, Primary Key: False
  - MID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - PID (TEXT), NOT NULL: False, Default: None, Primary Key: False
  - ID (INTEGER), NOT NULL: False, Default: None, Primary Key: False

# Write SQL queries for the following questions

## 1. Write query to list first 5 rows of Person table

In [7]:
q1 = "SELECT * FROM Person LIMIT 5;"
df=pd.read_sql_query(q1,conn)
df

   index        PID                   Name  Gender
0      0  nm0000288         Christian Bale    Male
1      1  nm0000949         Cate Blanchett  Female
2      2  nm1212722   Benedict Cumberbatch    Male
3      3  nm0365140          Naomie Harris  Female
4      4  nm0785227            Andy Serkis    Male

In [8]:
def q1_grader(q1):
  result = pd.read_sql_query(q1, conn)
  return result.shape == (5, 4)
print(q1_grader(q1))

True

## 2. Write query to select title, year and rating from Movie table

In [9]:
q2 = """SELECT title,year,rating FROM Movie;"""
df=pd.read_sql_query(q2,conn)
df

              title  year  rating
0            Mowgli  2018     6.6
1     Ocean's Eight  2018     6.2
2       Tomb Raider  2018     6.4
3      The Avengers  2012     8.1
4           Tumbbad  2018     8.5
...             ...   ...     ...
3468    Allah-Rakha  1986     6.2
3469          Anari  1993     4.7
3470  Come December  2006     5.7
3471     Kala Jigar  1939     3.3
3472         Kanoon  1994     3.2

[3473 rows x 3 columns]

In [10]:
def q2_grader(q2):
  result = pd.read_sql_query(q2, conn)
  return result.shape == (3473, 3) and result['title'][0]=='Mowgli'
print(q2_grader(q2))

True

## 3. Write query to get title of first movie in movie table sorted by year in ascending order

In [11]:
q3 = """
SELECT title
FROM Movie
ORDER BY year ASC
LIMIT 1;
"""
df=pd.read_sql_query(q3,conn)
df

      title
0  Alam Ara

In [12]:
def q3_grader(q3):
  result = pd.read_sql_query(q3, conn)
  return result['title']=='Alam Ara'
print(q3_grader(q3))

0    True
Name: title, dtype: bool

## 4. Write query to get the very first year in which Devdas movie was released

In [13]:
q4 = """
SELECT year
FROM Movie
WHERE title = 'Devdas'
ORDER BY year ASC
LIMIT 1;
"""
df=pd.read_sql_query(q4,conn)
df

   year
0  1936

In [14]:
def q4_grader(q4):
  result = pd.read_sql_query(q4, conn)
  return result['year']=='1936'
print(q4_grader(q4))

0    True
Name: year, dtype: bool

## 5. Write query to get the number of movies released in 2018

In [15]:
q5 = """
SELECT COUNT(*) AS movie_count
FROM Movie
WHERE year = '2018';
"""
df=pd.read_sql_query(q5,conn)
df

   movie_count
0           93

In [16]:
def q5_grader(q5):
  result = pd.read_sql_query(q5, conn)
  return result.iloc[0, 0] == 93
print(q5_grader(q5))

True

## 6. Write query to get the title of the movie with most number of votes in 2012

In [17]:
q6 = """
SELECT title
FROM Movie
WHERE year = '2012'
ORDER BY num_votes DESC
LIMIT 1;
"""
df=pd.read_sql_query(q6,conn)
df

          title
0  The Avengers

In [18]:
def q6_grader(q6):
  result = pd.read_sql_query(q6, conn)
  return result["title"]=="The Avengers"
print(q6_grader(q6))

0    True
Name: title, dtype: bool

## 7. Write SQL query to find all the unique movie titles released in 2018

In [19]:
q7 = """
SELECT DISTINCT title
FROM Movie
WHERE year = '2018';
"""
df=pd.read_sql_query(q7,conn)
df

                             title
0                           Mowgli
1                    Ocean's Eight
2                      Tomb Raider
3                          Tumbbad
4                        Kedarnath
..                             ...
88              Leera the Soulmate
89  Shaadi Teri Bajayenge Hum Band
90                       Aadamkhor
91           Vaibhav Sethia: Don't
92                Shohrat the Trap

[93 rows x 1 columns]

In [20]:
def q7_grader(q7):
  result = pd.read_sql_query(q7, conn)
  return result.shape==(93, 1)
print(q7_grader(q7))

True

## 8. Write SQL query to get total number of movies released between 2017 (inclusive) and 2018 (inclusive)

In [21]:
q8 = """
SELECT COUNT(*) AS total_movies
FROM Movie
WHERE year >= '2017' AND year <= '2018';
"""
df=pd.read_sql_query(q8,conn)
df

   total_movies
0           211

In [22]:
def q8_grader(q8):
  result = pd.read_sql_query(q8, conn)
  return result.iloc[0, 0] == 211
print(q8_grader(q8))

True

## 9. Write SQL query to find the year in which maximum number of movies released

In [23]:
q9 = """
SELECT year, COUNT(*) AS movie_count
FROM Movie
GROUP BY year
ORDER BY movie_count DESC
LIMIT 1;
"""
df=pd.read_sql_query(q9,conn)
df

   year  movie_count
0  2005          128

In [24]:
def q9_grader(q9):
  result = pd.read_sql_query(q9, conn)
  return result["year"][0]=="2005"
print(q9_grader(q9))

True

## 10. Write SQL query to find the title of the movie with rating>9.5 and number of votes > 90

In [27]:
q10 = """
SELECT title,rating,num_votes
FROM Movie
WHERE rating > 9.5
  AND num_votes > 90;
"""
df=pd.read_sql_query(q10,conn)
df

                    title  rating  num_votes
0  Man on Mission Fauladi     9.6         96

In [28]:
def q10_grader(q10):
  result = pd.read_sql_query(q10, conn)
  return result["title"][0]=="Man on Mission Fauladi"
print(q10_grader(q10))

True

## 11. Write SQL query to find the number of movies which has the word 'Dilwale' in their title

In [29]:
q11 = """
SELECT COUNT(*) AS movie_count
FROM Movie
WHERE title LIKE '%Dilwale%';
"""
df=pd.read_sql_query(q11,conn)
df

   movie_count
0            4

In [30]:
def q11_grader(q11):
  result = pd.read_sql_query(q11, conn)
  return result.iloc[0, 0] == 4
print(q11_grader(q11))

True

## 12. Write nested SQL query to find the CID of country which produced most number of movies

In [32]:
q12 = """
SELECT CID
FROM Country
WHERE CID = (
    SELECT CID
    FROM M_Country
    GROUP BY CID
    ORDER BY COUNT(*) DESC
    LIMIT 1
);
"""

df=pd.read_sql_query(q12,conn)
df

   CID
0    2

In [33]:
def q12_grader(q12):
  result = pd.read_sql_query(q12, conn)
  return result.iloc[0]==2.0
print(q12_grader(q12))

CID    True
Name: 0, dtype: bool

## 13. Write nested SQL query to the country which produced most number of movies (use both Courty table and M_Country table)

In [34]:
q13 = """
SELECT Name
FROM Country
WHERE CID = (
    SELECT CID
    FROM M_Country
    GROUP BY CID
    ORDER BY COUNT(*) DESC
    LIMIT 1
);
"""
df=pd.read_sql_query(q13,conn)
df

    Name
0  India

In [35]:
def q13_grader(q13):
  result = pd.read_sql_query(q13, conn)
  return result.iloc[0, 0] == "India"
print(q13_grader(q13))

True

## 14. Write SQL query to get the year and number of movies per year having number of movies per year is greater than 100

In [36]:
q14 = """
SELECT year, COUNT(*) AS movie_count
FROM Movie
GROUP BY year
HAVING COUNT(*) > 100;
"""
df=pd.read_sql_query(q14,conn)
df

    year  movie_count
0   2003          101
1   2004          103
2   2005          128
3   2007          104
4   2008          103
5   2010          117
6   2011          109
7   2012          108
8   2013          127
9   2014          118
10  2015          109
11  2016          118
12  2017          118

In [37]:
def q14_grader(q14):
  result = pd.read_sql_query(q14, conn)
  return result.shape==(13,2)
print(q14_grader(q14))

True

## 15. Write SQL query to get the Name and Language ID (LAID) corresponding to Malayalam language

In [38]:
q15 = """
SELECT Name, LAID
FROM Language
WHERE Name = 'Malayalam';
"""
df=pd.read_sql_query(q15,conn)
df

        Name  LAID
0  Malayalam    19

In [39]:
def q15_grader(q15):
  result = pd.read_sql_query(q15, conn)
  print(result)
  return result[["Name", "LAID"]].values.tolist() == [['Malayalam', 19]]
print(q15_grader(q15))

        Name  LAID
0  Malayalam    19
True

## 16. Write SQL query to do inner join with movie table and M_Language table with MID columns

In [40]:
q16 = """
SELECT *
FROM Movie
INNER JOIN M_Language
ON Movie.MID = M_Language.MID;
"""
df=pd.read_sql_query(q16,conn)
df

,index,MID,title,year,rating,num_votes,index,MID,LAID,ID
0,0,tt2388771,Mowgli,2018,6.6,21967,0,tt2388771,0,0
1,1,tt5164214,Ocean's Eight,2018,6.2,110861,1,tt5164214,0,1
2,2,tt1365519,Tomb Raider,2018,6.4,142585,2,tt1365519,0,2
3,3,tt0848228,The Avengers,2012,8.1,1137529,3,tt0848228,0,3
4,4,tt8239946,Tumbbad,2018,8.5,7483,4,tt8239946,1,4
...,...,...,...,...,...,...,...,...,...,...
3468,3470,tt0090611,Allah-Rakha,1986,6.2,96,3470,tt0090611,2,3470
3469,3471,tt0106270,Anari,1993,4.7,301,3471,tt0106270,2,3471
3470,3472,tt0852989,Come December,2006,5.7,57,3472,tt0852989,2,3472
3471,3473,tt0375882,Kala Jigar,1939,3.3,174,3473,tt0375882,2,3473
3472,3474,tt0375890,Kanoon,1994,3.2,103,3474,tt0375890,2,3474

In [41]:
def q16_grader(q16):
  result = pd.read_sql_query(q16, conn)
  return result
print(q16_grader(q16))

      index        MID          title  year  rating  num_votes  index  \
0         0  tt2388771         Mowgli  2018     6.6      21967      0
1         1  tt5164214  Ocean's Eight  2018     6.2     110861      1
2         2  tt1365519    Tomb Raider  2018     6.4     142585      2
3         3  tt0848228   The Avengers  2012     8.1    1137529      3
4         4  tt8239946        Tumbbad  2018     8.5       7483      4
...     ...        ...            ...   ...     ...        ...    ...
3468   3470  tt0090611    Allah-Rakha  1986     6.2         96   3470
3469   3471  tt0106270          Anari  1993     4.7        301   3471
3470   3472  tt0852989  Come December  2006     5.7         57   3472
3471   3473  tt0375882     Kala Jigar  1939     3.3        174   3473
3472   3474  tt0375890         Kanoon  1994     3.2        103   3474

            MID  LAID    ID
0     tt2388771     0     0
1     tt5164214     0     1
2     tt1365519     0     2
3     tt0848228     0     3
4     tt8239946     1     4
...         ...   ...   ...
3468  tt0090611     2  3470
3469  tt0106270     2  3471
3470  tt0852989     2  3472
3471  tt0375882     2  3473
3472  tt0375890     2  3474

[3473 rows x 10 columns]

## 17. Write SQL query to list title, year and rating of malayalam movies in the database by doing an inner join with movie table and M_Language table with MID column, also assuming language ID of malayalam movies as 19

In [42]:
q17 = """
SELECT Movie.title, Movie.year, Movie.rating
FROM Movie
INNER JOIN M_Language
ON Movie.MID = M_Language.MID
WHERE M_Language.LAID = 19;
"""
df=pd.read_sql_query(q17,conn)
df

                            title    year  rating
0                  Dil Hai Betaab    1993     4.6
1                        Chemmeen    1965     7.8
2                           Aryan    1988     7.2
3                       Kala Pani    1996     8.4
4                  Aadupuliyattam    2016     4.2
5                       New Delhi    1987     7.7
6                             Who  I 2018     7.1
7                     Cover Story    2000     5.8
8                        Vaishali    1988     7.7
9                     Maanthrikam    1995     6.3
10                      Abhimanyu    1991     7.1
11               Inspector Balram    1991     6.9
12               Satyameva Jayate    2000     5.3
13           Veettilekkulla Vazhi    2011     6.8
14  Alavuddinum Athbutha Vilakkum    1979     6.8
15                      The Train    2011     4.5

In [43]:
def q17_grader(q17):
  result = pd.read_sql_query(q17, conn)
  return result.shape==(16,3)
print(q17_grader(q17))

True

In [92]:
![ -f academic.db ] && rm academic.db

conn = sqlite3.connect("academic.db")
cursor = conn.cursor()

## 18. Write SQL query to Create a table named students with two columns id (integer type) and name (varchar type)

In [101]:
q18a = """
CREATE TABLE students (
    id INTEGER,
    name VARCHAR
);
"""
df=pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';",conn)
df

       name
0  students

In [94]:
def q18_grader_a(q18):
  try:
    cursor.execute(q18)
    return True
  except:
    pass

def q18_grader_b(q19):
  result = pd.read_sql_query(q19, conn)
  return result.columns.tolist() == ['id', 'name']

q18b = """SELECT * FROM students;"""

print(q18_grader_a(q18a) and q18_grader_b(q18b))

True

## 19. Write SQL query to insert the values (1, 'Alice') into students table

In [95]:
q19_a = """
INSERT INTO students (id, name)
VALUES (1, 'Alice');
"""

In [96]:
def q19_grader_a(q19_a):
  try:
    cursor.execute(q19_a)
  except:
    pass
  return True

def q19_grader_b(q19_b):
  result = pd.read_sql_query(q19_b, conn)
  return result.values.tolist() == [[1, 'Alice']]

q19_b = "SELECT * FROM students"
print(q19_grader_a(q19_a) and q19_grader_b(q19_b))

True

## 20. Write SQL Query to add the following more information to students table

| ID | Name    |
|----|---------|
| 2  | Bob     |
| 3  | Charlie |

In [102]:
q20 = """
INSERT INTO students (id, name)
VALUES
    (2, 'Bob'),
    (3, 'Charlie');
"""

In [73]:
def q20_grader(q20):
  try:
    cursor.execute(q20)
  except:
    pass
  return True

def q20_grader_b(q20_b):
  result = pd.read_sql_query(q20_b, conn)
  return result.values.tolist() == [[1, 'Alice'], [2, 'Bob'], [3, 'Charlie']]

print(q20_grader(q20) and q20_grader_b(q19_b))

True

In [ ]:
# conn.close()